apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftc-app

resources:
  - ../../base

images:
  - name: os-service
    newName: 305032652600.dkr.ecr.us-east-1.amazonaws.com/os-service
    newTag: latest

replicas:
  - name: os-service
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: development
    target:
      kind: ConfigMap
      name: os-service-config
